name: Powerball Sync

on:
  schedule:
    - cron: "0 4,16 * * *" # Daily twice
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node scripts/powerball.js

      - run: node scripts/stats.js powerball

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/powerball
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit. Skipping push."
            exit 0
          fi
          
          
          # Extract the draw date from the staged filename (e.g., data/powerball/2025-12-16.json)
          DRAW_DATE=$(git diff --name-only --cached | grep -E '[0-9]{4}-[0-9]{2}-[0-9]{2}\.json' | head -n 1 | xargs basename -s .json)
          
          if [ -z "$DRAW_DATE" ]; then
            DRAW_DATE=$(date +'%Y-%m-%d')
          fi
          
          git commit -m "Update Powerball data: $DRAW_DATE"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
